import json
import os
import re
from src import config
from src.llm_client import get_llm_client, get_llm_model, call_llm

def get_clean_words(text: str) -> set[str]:
    """Helper to tokenize text into a set of lowercased words."""
    words = re.findall(r'\b\w+\b', text.lower())
    # Exclude common stopwords to focus on content words
    stopwords = {"the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for", "with", "by", "of", "is", "are", "was", "were", "that", "this", "these"}
    return set(w for w in words if w not in stopwords)

def jaccard_overlap(gaps_a: list[dict], gaps_b: list[dict]) -> float:
    """
    Calculate lexical Jaccard similarity of vocabulary across two gap sets.
    """
    words_a = set()
    for g in gaps_a:
        words_a.update(get_clean_words(g.get("Claim", "")))
        
    words_b = set()
    for g in gaps_b:
        words_b.update(get_clean_words(g.get("Claim", "")))
        
    if not words_a or not words_b:
        return 0.0
        
    intersection = words_a.intersection(words_b)
    union = words_a.union(words_b)
    return len(intersection) / len(union)

def count_unique_gaps(gaps: list[dict]) -> int:
    """
    Group similar Claims using Sentence-BERT cosine similarity, falling back to word overlap Jaccard.
    """
    if not gaps:
        return 0
        
    claims = [g.get("Claim", "").strip() for g in gaps if g.get("Claim")]
    if not claims:
        return 0
        
    # Grouping using Sentence-BERT
    try:
        from sentence_transformers import SentenceTransformer
        import numpy as np
        
        model = SentenceTransformer('all-MiniLM-L6-v2')
        embeddings = model.encode(claims, show_progress_bar=False)
        
        # Calculate pairwise cosine similarities
        norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
        normalized = embeddings / (norms + 1e-8)
        similarity = np.dot(normalized, normalized.T)
        
        # Simple clustering: merge if similarity >= 0.85
        visited = set()
        unique_count = 0
        for i in range(len(claims)):
            if i in visited:
                continue
            unique_count += 1
            visited.add(i)
            for j in range(i + 1, len(claims)):
                if similarity[i, j] >= 0.85:
                    visited.add(j)
        return unique_count
        
    except Exception as e:
        print(f"[*] Embedding clustering failed: {e}. Falling back to token Jaccard clustering.")
        # Fallback: token Jaccard clustering
        visited = set()
        unique_count = 0
        
        claim_wordsets = [get_clean_words(c) for c in claims]
        
        for i in range(len(claims)):
            if i in visited:
                continue
            unique_count += 1
            visited.add(i)
            set_a = claim_wordsets[i]
            
            for j in range(i + 1, len(claims)):
                set_b = claim_wordsets[j]
                if not set_a or not set_b:
                    continue
                overlap = len(set_a.intersection(set_b)) / len(set_a.union(set_b))
                if overlap >= 0.40: # Lexical overlap threshold
                    visited.add(j)
        return unique_count

def evaluate_nli_entailment_rate(gaps: list[dict], method_name: str) -> float:
    """
    Use LLM as an NLI model to evaluate if: Grounds + Warrant ==> Claim.
    """
    if not gaps:
        return 0.0
        
    print(f"[*] Running NLI Entailment evaluation on {len(gaps)} gaps generated by {method_name}...")
    entailed_count = 0
    total_valid = 0
    
    for idx, g in enumerate(gaps):
        grounds = g.get("Grounds", "")
        warrant = g.get("Warrant", "")
        claim = g.get("Claim", "")
        
        if not grounds or not claim:
            continue
            
        total_valid += 1
        prompt = f"""
        You are a strict formal logic evaluator. Evaluate if the Conclusion (Claim) is logically entailed by the Premises (Grounds + Warrant).
        "Entailment" means the Claim is a direct, logical, and reasonable consequence of the Grounds and Warrant, without requiring huge leaps of faith.
        
        Premises:
        - Grounds: {grounds}
        - Warrant: {warrant}
        
        Hypothesis / Conclusion:
        - Claim: {claim}
        
        Output strictly as a JSON object with two fields (no markdown formatting, backticks, or other explanation):
        {{
          "logical_relationship": "One of: ENTAILMENT, NEUTRAL, CONTRADICTION",
          "reason": "A brief one-sentence reason."
        }}
        """
        
        try:
            content = call_llm(prompt, temperature=0.0)
            if content.startswith("```"):
                lines = content.split("\n")
                if lines[0].startswith("```json") or lines[0].startswith("```"):
                    content = "\n".join(lines[1:-1])
                    
            result = json.loads(content)
            relation = result.get("logical_relationship", "").strip().upper()
            
            if relation == "ENTAILMENT":
                entailed_count += 1
                
        except Exception as e:
            # Fallback on API error: default to neutral
            pass
            
    if total_valid == 0:
        return 0.0
        
    rate = entailed_count / total_valid
    print(f"[+] NLI Entailment Rate for {method_name}: {rate:.2f} ({entailed_count}/{total_valid})")
    return rate

def run_evaluation():
    # Load all gap sets
    gaps_kgtabi = []
    gaps_mulla_rag = []
    gaps_simple_llm = []
    gaps_gapmap = []
    
    paths = {
        "KG-TABI (Ours)": os.path.join(config.GAPS_DIR, "kgtabi_gaps.json"),
        "B1 (Mulla RAG)": os.path.join(config.GAPS_DIR, "baseline_mulla_rag.json"),
        "B2 (Simple LLM)": os.path.join(config.GAPS_DIR, "baseline_simple_llm.json"),
        "B3 (GAPMAP Text)": os.path.join(config.GAPS_DIR, "baseline_gapmap.json"),
        "B4 (GraphRAG)": os.path.join(config.GAPS_DIR, "baseline_graphrag.json"),
        "B5 (LightRAG)": os.path.join(config.GAPS_DIR, "baseline_lightrag.json"),
        "B6 (HippoRAG)": os.path.join(config.GAPS_DIR, "baseline_hipporag.json"),
    }
    
    all_gaps = {}
    for name, path in paths.items():
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                all_gaps[name] = json.load(f)
        else:
            all_gaps[name] = []
            print(f"[!] Warning: Gap file for '{name}' not found at {path}. Metric will show 0.")

    # Calculate statistics
    report_data = []
    
    for name, gaps in all_gaps.items():
        total_gaps = len(gaps)
        unique_gaps = count_unique_gaps(gaps)
        
        # Calculate mean gap description length (Claim word count)
        claim_lengths = [len(g.get("Claim", "").split()) for g in gaps if g.get("Claim")]
        avg_len = sum(claim_lengths) / len(claim_lengths) if claim_lengths else 0.0
        
        # Calculate NLI entailment rate
        nli_rate = evaluate_nli_entailment_rate(gaps, name) if gaps else 0.0
        
        # Jaccard overlap vs KG-TABI
        jaccard_vs_kg = 1.0
        if name != "KG-TABI (Ours)":
            jaccard_vs_kg = jaccard_overlap(all_gaps.get("KG-TABI (Ours)", []), gaps)
            
        report_data.append({
            "Method": name,
            "Total Gaps": total_gaps,
            "Unique Gaps": unique_gaps,
            "Avg Words/Claim": f"{avg_len:.1f}",
            "NLI Entailment Rate": f"{nli_rate * 100:.1f}%",
            "Jaccard Overlap vs KG-TABI": f"{jaccard_vs_kg:.3f}" if name != "KG-TABI (Ours)" else "N/A"
        })
        
    # Build Markdown table
    markdown = "# Experimental Evaluation Results\n\n"
    markdown += "This report summarizes the comparison between our proposed **KG-TABI** framework and the baselines.\n\n"
    markdown += "| Method | Total Gaps | Unique Gaps | Avg Words/Claim | NLI Entailment Rate | Jaccard Overlap vs KG-TABI |\n"
    markdown += "| :--- | :---: | :---: | :---: | :---: | :---: |\n"
    
    for r in report_data:
        markdown += f"| **{r['Method']}** | {r['Total Gaps']} | {r['Unique Gaps']} | {r['Avg Words/Claim']} | {r['NLI Entailment Rate']} | {r['Jaccard Overlap vs KG-TABI']} |\n"
        
    output_path = os.path.join(config.DATA_DIR, "evaluation_results.md")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(markdown)
        
    print(f"\n[+] Saved evaluation report to {output_path}")
    print(markdown)

if __name__ == "__main__":
    run_evaluation()
